version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: github_assistant_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: github_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: github_assistant_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: github_assistant_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage


volumes:
  postgres_data:
  redis_data:
  qdrant_data:
